describe('tracalorie', () => {
    // beforeEach(() => {
    //     cy.visit('https://practice.expandtesting.com/bmi')
    // })

    it('TC-01', () => {
        cy.visit('https://practice.expandtesting.com/bmi')
        cy.get('#gender').select('Male')
        cy.get('#age').clear()
        cy.get('#age').type('21')
        cy.get('#height').clear()
        cy.get('#height').type('180')
        cy.get('#weight').clear()
        cy.get('#weight').type('67')
        cy.get('.btn-primary').click()
    })
    it('TC-02', () => {
        cy.visit('https://practice.expandtesting.com/bmi')
        // cy.get('#gender').select('Male')
        // cy.get('#age').clear()
        // cy.get('#age').type('21')
        // cy.get('#height').clear()
        // cy.get('#height').type('180')
        // cy.get('#weight').clear()
        // cy.get('#weight').type('67')
        cy.get('.btn-secondary').click()
    })
    it('TC-03', () => {
        cy.visit('https://practice.expandtesting.com/bmi')
        cy.get('#gender').select('Male')
        cy.get('#age').clear()
        cy.get('#age').type('21')
        cy.get('#height').clear()
        cy.get('#height').type('180')
        cy.get('#weight').clear()
        cy.get('#weight').type('67')
        cy.get('.btn-primary').click()
        cy.get('.btn-secondary').click()
    })
    it.only('TC-04', () => {
        cy.visit('https://practice.expandtesting.com/bmi')
        cy.get('#gender').select('Male')
        cy.get('#age').clear()
        cy.get('#age').type('21')
        cy.get('#height').clear()
        cy.get('#height').type('180')
        cy.get('#weight').clear()
        cy.get('#weight').type('67')
        cy.get('.btn-primary').click()
        cy.get('.btn-secondary').click()
        cy.wait(5000)
        cy.get('#gender').select('Female')
        cy.get('#age').clear()
        cy.get('#age').type('18')
        cy.get('#height').clear()
        cy.get('#height').type('162')
        cy.get('#weight').clear()
        cy.get('#weight').type('52')
        cy.get('.btn-primary').click()
    })
    

})
